services:
  web:
    restart: always
    image: ghcr.io/dalibo/explain.dalibo.com:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    links:
      - postgres:postgres
    volumes:
      - .:/app
    environment:
      DB_SERVICE: postgres

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
